### ISSUE TITLE
v1-2. 게임 오프닝, 사용자 입력

### ISSUE THREAD

**Issue by yewonbahn** [shinhanpro/pig-dice-game#4]
### TODO

- [x] 게임 환영 메시지 출력 
- [x] 게임에 참여할 인원 `n` 입력 받기
- [x] 사용자 이름 `user_name` 입력 받기 
- [x] 총 타켓 점수 `target_score` 입력받기
